site_name: HPCC-Unical Documentation
repo_url: https://github.com/HPCC-Unical/Docs.git
edit_uri: ""
site_url: 
site_dir: docs
docs_dir: src
site_author: "HPCC-Unical"
remote_branch: production
site_description: >-
  Documentation of the HCP resources at Unical
copyright: Copyright &copy; 2022 &#8282; HPCC-Unical
nav:
  - Home: index.md
  - Resources:
    - Overview: resources/overview.md
    - Access: resources/access.md 
    - Newton: 
      - Architecture: resources/newton/architecture.md
      - Accounts: resources/newton/accounts.md
      - Run: resources/newton/run.md
      - Module system: resources/newton/software.md
  - Support: support.md
  - Known issues: known_issues.md
theme:
  name: material
  custom_dir: overrides
  greetings: Welcome to the HPC at Unical
  language: en

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
  
  palette:
        scheme: black
        primary: light blue
        accent: light blue

      #font: false

  favicon: images/favicon.png

  icon:
    logo: logo
  
      #home_primary:
      #title: Get Started
      #page: firststeps/getstarted/
      #home_secondary:
      #title: LUMI Overview
      #page: generic/overview/

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - tables
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
              custom_icons:
                      - overrides/.icons
